### ISSUE TITLE
Bruh fix it ;-; 

### ISSUE THREAD

**Issue by Mak365-hash** [oonqt/condo-uploader#3]
(node:8856) UnhandledPromiseRejectionWarning: TypeError: FileAsync_1.default is not a constructor
    at C:\Users\Broken\Documents\UploadCOns\uploader.js:75:27
    at step (C:\Users\Broken\Documents\UploadCOns\uploader.js:33:23)
    at Object.next (C:\Users\Broken\Documents\UploadCOns\uploader.js:14:53)
    at C:\Users\Broken\Documents\UploadCOns\uploader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Broken\Documents\UploadCOns\uploader.js:4:12)
    at C:\Users\Broken\Documents\UploadCOns\uploader.js:70:23
    at Object.<anonymous> (C:\Users\Broken\Documents\UploadCOns\uploader.js:229:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by oonqt** [comment]
What is your use for this? You're compiling it incorrectly, this has nothing to do with the code.

**Comment by Mak365-hash** [comment]
All im doing is tsc uploader.ts

**Comment by Mak365-hash** [comment]
what should the command be?

**Comment by Mak365-hash** [comment]
Do you have a discord I can contact you with?

**Comment by oonqt** [comment]
JS(s)#0163

**Comment by Mak365-hash** [comment]
The # is not correct

**Comment by oonqt** [comment]
JS(s)#0163 somehow the zero got cut off

**Comment by Mak365-hash** [comment]
And sent!
